### ISSUE TITLE
Glitch with choosing what pokemon generation to guess

### ISSUE THREAD

**Issue by nd23810** [Fireblend/squirdle#11]
Hey!

Sometimes when you choose to do a specific generation (for example, guessing Pokemon from Gen 1 to Gen 1, or Gen 4 to Gen 6) the "right" Pokemon will be from a different generation. (Last time I checked, Meltan was NOT a gen 1 Pokemon.)

**Comment by Fireblend** [comment]
Good catch! Should be working now.

**Comment by nd23810** [comment]
It is! Thanks.
