### ISSUE TITLE
[Feature Request] Put spoiler tags around share with guesses ("Discord format")

### ISSUE THREAD

**Issue by Googer** [Fireblend/squirdle#12]
The ability to share with guesses is great, but even better would be if they could be enclosed in spoiler tags (double bars - `||`) so when sharing on Discord they're not immediately visible to others that see the message without clicking / tapping on the spoiler'd section) - something like this would be perfect (copied then modified from a practice Squirdle):

Squirdle 6/8

🔽🟥🟥🔽🔽 ||Empoleon||
🟩🟥🟥🔼🔼 ||Houndour||
🟩🟥🟥🔼🔼 ||Delibird||
🟩🟥🟥🔽🔼 ||Heracross||
🟩🟥🟩🟩🔼 ||Ampharos||
🟩🟩🟩🟩🟩 ||Stantler||

I don't think this is considered standard Markdown though (and should be considered Discord-specific) but given its ubiquity these days (and especially likely among Squirdle's playerbase) this would be appreciated. 🙂

**Comment by Fireblend** [comment]
I thought about it, but ended up omitting the pipes syntax as they're not that much effort to edit in for Discord users and keeps the sharing format universal. I've seen some people use that option to share results of free play games on Twitter, which is pretty harmless, so there *are* players using it in other contexts.
