### ISSUE TITLE
[Feature Request] Input names in other languages

### ISSUE THREAD

**Issue by lens0021** [Fireblend/squirdle#14]
Thank you for developing and maintaining this project!

It will be nice if it is possible to submit pokemon by its foreign names, for example, Japanese.

You can query a map from English to Japanese in Wikidata(CC0; Public domain) in any format including CSV, TSV, and JSON: https://w.wiki/4shc

pokemon | label | label2 | pokedexNumber
-- | -- | -- | --
wd:Q847571 | Bulbasaur | フシギダネ | 001
wd:Q1636903 | Ivysaur | フシギソウ | 002
wd:Q2283930 | Venusaur | フシギバナ | 003
wd:Q3178753 | Charmander | ヒトカゲ | 004

My goal for this is for another language(Korean), so general i18n is the perfect solution.

Thank you.

**Comment by Fireblend** [comment]
I would envision this as an alternate route for the webapp, something like `squirdle.fireblend.com/jp/free` and `squirdle.fireblend.con/jp/daily` with the language component being a dynamic flask URL resource that determines which CSV column to pull from for suggestions, comparisons, etc. If someone could enhance the existing pokedex csv with the appropriate alternate language columns, I'd be happy to put the rest in my to-do list. I'd rather pull info from the static csv resource than an API.

**Comment by lens0021** [comment]
I can add new columns for alternate languages if you make sure that it is not a matter of the number of columns being too large.

**Comment by lens0021** [comment]
> I would envision this as an alternate route for the webapp, something like `squirdle.fireblend.com/jp/free` and `squirdle.fireblend.con/jp/daily` with the language component being a dynamic flask URL resource that determines which CSV column to pull from for suggestions, comparisons, etc.

I didn't expect the description, the instrumentation and the title could be translated. I expected just the names of Pokémons in other languages. Could I ask you exactly what is added to your to-do list?

**Comment by Fireblend** [comment]
As you said, just the names, shouldn't be hard to handle and implement. Please note however that the code is currently "frozen" as I'm working on a Javascript version of the game to alleviate server costs. Once that is done I can get to work on new features like this! Cheers, and thanks for your patience!

**Comment by patarapolw** [comment]
Actually, I have just done it in Japanese, but of course, I am just a learner, not a native. Purely client side as well. I also make sure that [localization is easy](https://github.com/patarapolw/squirdle/blob/pure-js/translation.json).

https://github.com/patarapolw/squirdle/tree/pure-js

https://ja-squirdle.vercel.app/

**Comment by Fireblend** [comment]
> https://github.com/patarapolw/squirdle/tree/pure-js
https://ja-squirdle.vercel.app/

This is great! I've been working on getting a JS/client-side version of the page working with my mediocre js skills but this seems much cleaner. Good job! Will you be maintaining your own fork of the english version?

**Comment by patarapolw** [comment]
> Will you be maintaining your own fork of the english version?

I finally made it multilingual and that includes English. It is at <https://squirdle.polv.cc>. [I also used your daily data for English.](https://github.com/patarapolw/squirdle/blob/main/scripts/normalize-fake-daily.js)

**Comment by Fireblend** [comment]
This is done! Started with Japanese and Korean, based on @patarapolw 's repo data. If anyone is able to provide a mapping file similar to the ja.json or ko.json files added under the /data directory in the repo for another language, I'd be happy to add it to the site.
