### ISSUE TITLE
[Feature request] show "keyboard" of possible types

### ISSUE THREAD

**Issue by CC007** [Fireblend/squirdle#19]
Just like you can see possible letters in Wordle, it would be nice if you saw a "keyboard" of possible types.

**Comment by CC007** [comment]
And possibly that it would highlight the types of the selected pokemon, before submitting

**Comment by CC007** [comment]
Maybe make it a toggle, because some people might want to play without this extra info.

**Comment by Fireblend** [comment]
This has been added to the latest version!

**Comment by Flexo013** [comment]
Feature looks great on Firefox, but this is the result on Chrome:

![image](https://user-images.githubusercontent.com/4507015/157116665-dd0a370d-06b3-471e-9199-f86544bed6f6.png)

Could this be fixed or should I make a separate issue for that?

**Comment by Fireblend** [comment]
@Flexo013 this looks like a cache issue. I would recommend clearing your cache and refreshing the page.

**Comment by Flexo013** [comment]
That works! Thanks!
