### ISSUE TITLE
Daily mosaics not obscuring generation

### ISSUE THREAD

**Issue by jake-white** [Fireblend/squirdle#22]
Noticed this starting a couple days ago. On the daily, it says

> Generation hint arrows are obscured in daily
mosaics to avoid spoiling other players!

And this used to be the case, replacing the arrows with blue box emojis. However here are my pastes from today's daily, it happens with both buttons.

Squirdle Daily 50 - 7/8
🔽🟥🟥🔽🔼
🟩🟥🟥🔼🔽
🟩🟥🟥🔼🔼
🟩🟥🟥🔽🔽
🟩🟥🟥🔽🔼
🟩🟥🟥🔽🔽
🟩🟩🟩🟩🟩

Squirdle Daily 50 - 7/8
🔽🟥🟥🔽🔼Swanna
🟩🟥🟥🔼🔽Lairon
🟩🟥🟥🔼🔼Kirlia
🟩🟥🟥🔽🔽Flygon
🟩🟥🟥🔽🔼Dusclops
🟩🟥🟥🔽🔽Blaziken
🟩🟩🟩🟩🟩Dustox

**Comment by Fireblend** [comment]
Fixed! Thanks for the heads up.
