### ISSUE TITLE
[Minor bug] wrong emoji used for generation

### ISSUE THREAD

**Issue by CC007** [Fireblend/squirdle#23]
When sharing the results I found that it doesn't display arrows for the generation, like it does for height and weight.  Instead it shows a blue square. 

This happens both for sharing with or without names.

For example,
Squirdle Daily 50 - 4/8
🟦🟥🟥🟩🔽Lucario
🟦🟥🟥🟩🔼Bayleef
🟩🟥🟥🟩🔼Pelipper
🟩🟩🟩🟩🟩[REDACTED]

**Comment by Fireblend** [comment]
This is not a bug, it's intended to not give too much away on daily challenge results.

**Comment by CC007** [comment]
When you share with names you can kinda infer if it should have been an up or down arrow, so it doesn't give away too much in that case
