### ISSUE TITLE
[Feature Request] Better Automatic Name Completion

### ISSUE THREAD

**Issue by mvfki** [Fireblend/squirdle#26]
So my pokemon today was "Dusk Mane Necrozma". After six rounds of guess, actually I was pretty sure what the answer was. The issue is, I'm not an English player, I knew that the original name should be Necrozma, and I knew the answer should be the alternative form, However, it was quite hard for me to figure out what I should type to reach to the correct answer. So what I think would be a good new feature is, when I type "Necr...", the drop-down list can not only show me "Necrozma", but also other possible answers including "Necr" in the middle, such as the correct answer today. So, just to change the matching from the start of the string to from anywhere in the string.

**Comment by Fireblend** [comment]
This has been implemented!
