### ISSUE TITLE
Add support for !, < and > in attribute filter

### ISSUE THREAD

**Issue by CC007** [Fireblend/squirdle#27]
For gen, weight and height allow the ability to use less than or greater than symbols, for example `gen<5` or `gen:<5`, whichever notation the dev prefers. Also allow negative filters, like `type1:!water` (and possibly `type:!water`) meaning that it won't show water (primary) type Pokemon.

**Comment by patarapolw** [comment]
> possibly `type:!water`

It can't understand why simply `type:water` wouldn't be there in the first place.

**Comment by CC007** [comment]
type: water would be a nice alias for type1:water type2: none, but out of scope for this feature request.

**Comment by CC007** [comment]
Using `type!water` is easier to type,
