### ISSUE TITLE
Incorrect Height and Weight Data

### ISSUE THREAD

**Issue by palimer6** [Fireblend/squirdle#29]
The Height and Weight data for Mega Gardevoir, Origin Forme Dialga, and Origin Forme Palkia seem to be wrong.

Mega Gardevoir is listed as 3.3m/325kg and should be 1.6m/48.4kg, just like regular Gardevoir.
Those values seem to be copied from Black Kyurem for some reason.

Dialga and Palkia Origin Formes are listed as the same as their base forms.
According to the official Website of the game:
[Dialga is 7.0m/850.0kg](https://legends.pokemon.com/en-gb/pokemon/dialga/)
[Palkia is 6.3m/660.0kg](https://legends.pokemon.com/en-gb/pokemon/palkia/)

**Comment by Fireblend** [comment]
Fixed.
