### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by kevinlinxc** [Fireblend/squirdle#36]
I'm new the game and normally wordle games have a help dialogue that can be activated to learn how to play the game. Does squirdle have this?

**Comment by Fireblend** [comment]
Hey Kevin. The game is somewhat self-explanatory once you play a couple times, but there's an Emoji Key tooltip you can see if you hover over the "Emoji Key" text near the game's header, and there should also be a link to an guide on using the advanced filters you can use to narrow down your guess. Hope that helps!
