### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by maxoku** [Fireblend/squirdle#37]
It just stopped working yesterday. Clearing cache doesn't help. Free play is the same.
![image](https://user-images.githubusercontent.com/17256400/163672879-10dbdb8d-9b8a-46b6-a4a6-58dba8af6162.png)

**Comment by Fireblend** [comment]
Hey there! I believe this might be an issue with an adblocker or another browser extension. I'll be pushing an update soon to try and fix it, but for now, if you're using an adblocker, you might want to either whitelist the page, or use incognito mode (if you're not using an adblocker, try using incognito anyway!). Sorry for the inconvenience!

**Comment by maxoku** [comment]
I've just figured out it was build-in tracking blocking in the Vivaldi browser. I've disabled it for squirdle and now it works. You could add an info to also add squirdle as exception for addons and build-in blocking functions.

**Comment by Fireblend** [comment]
I believe the issue comes from one of the project files being called "cookies.js". I assume ad blockers and other such extensions have a blanket filter for files with similar names. I have renamed the file and hope that will help. If not, I can always add a notice as you suggest.
