### ISSUE TITLE
Game Day Changing Based on UTC Time, Not Local

### ISSUE THREAD

**Issue by mike-welch** [Fireblend/squirdle#39]
I have been playing Squirdle on a daily basis with a discord group for the past 4-6 weeks. We enjoy the camaraderie and strategizing to try and one-up each other.

While we all typically play in the morning and send our results by 10am, sometimes life gets in the way and one of us won't get to it until the evening. Sometimes, when this happens, we have noticed that the game day in the mosaic is different. 

For example, for today (Apr 30, game day 109) I had the following:

Squirdle Daily 109 - 4/8
🟦🟥🟥🔼🔼
🟦🟥🟩🔽🔽
🟩🟥🟩🟩🔽
🟩🟩🟩🟩🟩

Meanwhile, our delayed friend had:
Squirdle Daily 110 - 3/8
🟦🟥🟥🔽🔽
🟦🟩🟥🔼🔼
🟩🟩🟩🟩🟩

Curiously, the mystery Pokémon was the same (she believes she had actually opened the webpage earlier in the day). We performed some quick testing with incognito windows and different browsers and were able to play the game for May 1 (game day 110). On a hunch, I went back and copied the (original) mosaic again from my phone (reloaded the page), and the game day had changed from 109 to 110 but was mosaic for day 109. 

Suspecting a bug, I took a look at the HTML and came across the following line:

https://github.com/Fireblend/squirdle/blob/131e35cf8dcd09783e01a2f7d8251af182f29d2c/daily.html#L107

I believe what's happening is that once the UTC date changes the game is advancing forward a day, even if the date hasn't changed in your local time zone. We're in EDT, so another hour to go at time of posting. If you already finished a game that day then it won't reset until midnight local time and if you start a new game (or refresh the webpage before finishing) you would advance to tomorrow's game.

For the above snippet, I think striking "ISO" and using the `toString` method will resolve this issue.

**Comment by ftick** [comment]
Replacing `toISOString().split("T")[0]` with `toLocaleDateString()` lets the game detect day changes based on local time btw
