### ISSUE TITLE
Type issue for Gen 1 Pokemon

### ISSUE THREAD

**Issue by SethSanchez** [Fireblend/squirdle#6]
Jigglypuff in Gen 1 was Normal only. The 15 available types in Gen 1 are:

Bug, 
Dragon, 
Electric, 
Fighting, 
Fire, 
Flying, 
Ghost, 
Grass, 
Ground, 
Ice, 
Normal, 
Poison, 
Psychic, 
Rock,
Water

Some types should be disabled in that mode.

**Comment by Fireblend** [comment]
As far as I'm concerned the types in the latest national dex are the only correct ones and the old ones have been "retconned". Having alternative CSV files would be a pain and implementing this would introduce ambiguity without explaining it properly to players or offering the option of toggling between old/new types, and the last thing I want to do is introduce more complexity/un-intuitiveness. I'd be open to someone submitting a pull request if they feel they can pull it off while considering the above though!

**Comment by SethSanchez** [comment]
Makes sense, appreciate the response.
