### ISSUE TITLE
[Feature Request] Copy guesses

### ISSUE THREAD

**Issue by paperfairy** [Fireblend/squirdle#7]
When I'm sharing the results with friends, I click "Share Result". It would be useful if there was another button, that allowed me to Share Results including the guesses I made. As of now, I have to click the button, paste it into a text box, and then type out all of my guesses. On mobile, this is particlarly painful. Here is a screenshot showing the use case.

Thanks! Love this game.

![image](https://user-images.githubusercontent.com/3393711/153642526-9911de79-4b07-4a4a-9b2b-7d0805ca92d5.png)

**Comment by charleslee94** [comment]
+1

**Comment by Fireblend** [comment]
Implemented!
